global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    projeto: pethub

rule_files:
  - /etc/prometheus/alertas.yml

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: pethub-api
    metrics_path: /metrics
    static_configs:
      - targets: ['backend:3000']
        labels:
          servico: api
